# Libraries for Neural Networks - sklearn 2 (regression)


## Loading the data

https://www.cs.toronto.edu/~delve/data/boston/bostonDetail.html

In [1]:
from sklearn.neural_network import MLPRegressor
from sklearn import datasets

In [2]:
boston = datasets.load_boston()

In [3]:
inputs = boston.data
inputs

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [4]:
boston.feature_names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [5]:
outputs = boston.target
outputs

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [6]:
boston.target_names

AttributeError: target_names

In [7]:
inputs.shape

(506, 13)

In [8]:
outputs.shape

(506,)

## Train and test datasets

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs, outputs, test_size = 0.2)

In [10]:
X_train.shape

(404, 13)

In [11]:
y_train.shape

(404,)

In [12]:
X_test.shape

(102, 13)

In [13]:
y_test.shape

(102,)

In [15]:
max(X_train[0]) , min(X_train[0])

(383.73, 0.0)

In [16]:
from sklearn.preprocessing import MinMaxScaler
scaler1 = MinMaxScaler()
X_train = scaler1.fit_transform(X_train)
X_test = scaler1.transform(X_test)

In [18]:
max(X_train[0]), min(X_train[0])

(0.9667910635937265, 0.0)

In [19]:
y_train = y_train.reshape(-1, 1)
y_test = y_test.reshape(-1, 1)

In [20]:
y_train.shape

(404, 1)

In [21]:
scaler2 = MinMaxScaler()
y_train = scaler2.fit_transform(y_train)
y_test = scaler2.transform(y_test)

In [22]:
max(y_train[0])

0.4266666666666667

## Neural network (training)

In [23]:
(13 + 1) / 2

7.0

In [24]:
network = MLPRegressor(max_iter=2000, verbose=True, hidden_layer_sizes=(7))
network.fit(X_train, y_train)

Iteration 1, loss = 0.32374304
Iteration 2, loss = 0.29938335
Iteration 3, loss = 0.27660762
Iteration 4, loss = 0.25513235
Iteration 5, loss = 0.23488780
Iteration 6, loss = 0.21597029
Iteration 7, loss = 0.19814105
Iteration 8, loss = 0.18163474
Iteration 9, loss = 0.16614499
Iteration 10, loss = 0.15170619
Iteration 11, loss = 0.13812539
Iteration 12, loss = 0.12560102
Iteration 13, loss = 0.11413411
Iteration 14, loss = 0.10366426
Iteration 15, loss = 0.09385805
Iteration 16, loss = 0.08492731
Iteration 17, loss = 0.07677889
Iteration 18, loss = 0.06945588
Iteration 19, loss = 0.06293291
Iteration 20, loss = 0.05719940
Iteration 21, loss = 0.05195425
Iteration 22, loss = 0.04729685
Iteration 23, loss = 0.04316466
Iteration 24, loss = 0.03960561
Iteration 25, loss = 0.03669808
Iteration 26, loss = 0.03423664
Iteration 27, loss = 0.03215868
Iteration 28, loss = 0.03042378
Iteration 29, loss = 0.02896731
Iteration 30, loss = 0.02787397
Iteration 31, loss = 0.02687066
Iteration 32, los

MLPRegressor(hidden_layer_sizes=7, max_iter=2000, verbose=True)

In [36]:
network.score(X_train,y_train)

0.2496342813168706

In [37]:
network.score(X_test,y_test)

0.19188485166314895

In [25]:
network.coefs_

[array([[-0.07666886,  0.11872718,  0.14279577, -0.43211564,  0.20911126,
         -0.41969997,  0.33602764],
        [ 0.30397416,  0.37306821, -0.28213515,  0.20561199,  0.24405293,
         -0.06806158,  0.2959383 ],
        [-0.18543791, -0.19736857, -0.25927727,  0.0371245 , -0.33186418,
         -0.44755277,  0.04661528],
        [-0.09636373,  0.47472057,  0.0883073 ,  0.2044689 , -0.03079812,
          0.23571634,  0.03470293],
        [ 0.34679167,  0.32686627, -0.00763517,  0.10322446,  0.45831834,
         -0.27200354,  0.45069486],
        [ 0.13393004, -0.10515513,  0.17103296, -0.37786179,  0.47050075,
          0.08555768,  0.40277389],
        [ 0.29224248, -0.02479129, -0.34069114,  0.35990458,  0.11350216,
          0.39827779,  0.00836564],
        [-0.31013046,  0.42622137,  0.27758237,  0.06312055,  0.21508196,
          0.12711847, -0.15426003],
        [ 0.11834481,  0.08720985,  0.4587368 , -0.51571053, -0.22608125,
         -0.60145598,  0.02694748],
        [-

In [26]:
network.intercepts_

[array([ 0.65417781, -0.33874665,  0.04177009, -0.28205119,  0.38643821,
        -0.03295152, -0.34092345]),
 array([-0.4045664])]

In [27]:
network.n_layers_

3

In [28]:
network.n_outputs_

1

In [29]:
network.out_activation_

'identity'

## Neural network (evaluation)

In [30]:
X_test.shape

(102, 13)

In [31]:
predictions = network.predict(X_test)
predictions

array([ 0.32810431,  0.40572304,  0.43515221,  0.48155919,  0.40804738,
        0.39564298,  0.39316684,  0.40252078,  0.43204794,  0.41309705,
        0.47057823,  0.36583299,  0.48297151,  0.44077585,  0.39374069,
        0.39006926,  0.51895645,  0.54131428,  0.03043919,  0.43278577,
        0.53535649,  0.4428145 ,  0.04510756,  0.33264623,  0.48455775,
        0.54428293,  0.07443558,  0.33032554,  0.57046803,  0.39037717,
        0.4070274 ,  0.28113967,  0.26460282,  0.47747794,  0.39277133,
        0.45632042,  0.5118447 ,  0.14955952,  0.32664608,  0.08592066,
        0.4122832 ,  0.28691097,  0.56932471,  0.37588065,  0.33318793,
        0.3907071 ,  0.42309795,  0.44322022,  0.3977019 ,  0.40703959,
        0.51239887,  0.52255277,  0.35396951,  0.4087729 ,  0.47154104,
        0.41214408,  0.3292376 ,  0.35062201,  0.40137514,  0.32791666,
        0.30420599,  0.17007935,  0.44973665,  0.34881882,  0.51676895,
        0.37850955,  0.39084992,  0.33776815,  0.45680004,  0.18

In [32]:
y_test

array([[0.28444444],
       [0.67555556],
       [0.22666667],
       [0.81555556],
       [0.39777778],
       [0.32222222],
       [0.48222222],
       [0.32666667],
       [0.69333333],
       [0.40222222],
       [1.        ],
       [0.4       ],
       [0.38888889],
       [0.61111111],
       [0.41777778],
       [0.27555556],
       [0.6       ],
       [0.42      ],
       [0.27111111],
       [0.77333333],
       [0.66444444],
       [0.53555556],
       [0.31111111],
       [0.20444444],
       [0.55111111],
       [0.42444444],
       [0.12      ],
       [0.32444444],
       [0.84666667],
       [0.14444444],
       [0.5       ],
       [0.42      ],
       [0.40888889],
       [0.37777778],
       [0.28444444],
       [0.59111111],
       [0.48      ],
       [0.40222222],
       [0.11555556],
       [0.21111111],
       [0.34444444],
       [0.31777778],
       [0.62      ],
       [0.34222222],
       [0.26      ],
       [0.52222222],
       [1.        ],
       [1.   

In [33]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
mean_absolute_error(y_test, predictions)

0.1426459550255563

In [34]:
mean_squared_error(y_test, predictions)

0.034904914790524495

In [35]:
import numpy as np
np.sqrt(mean_squared_error(y_test, predictions))

0.18682857059487581

## Neural network (classification)

In [38]:
X_test[0], y_test[0]

(array([0.10089527, 0.        , 0.64662757, 1.        , 0.79218107,
        0.50795171, 0.97234043, 0.0902618 , 1.        , 0.91412214,
        0.80851064, 0.95166171, 0.43495146]),
 array([0.28444444]))

In [39]:
X_test[0].shape

(13,)

In [40]:
new = X_test[0].reshape(1, -1)
new.shape

(1, 13)

In [41]:
network.predict(new)

array([0.32810431])

In [42]:
scaler2.inverse_transform(network.predict(new).reshape(-1,1))

array([[19.76469384]])

In [43]:
scaler2.inverse_transform(y_test[0].reshape(-1,1))

array([[17.8]])